import streamlit as st
from fpdf import FPDF

class SessionState:
    def __init__(self):
        self.username = None
        self.is_doctor = None

def login_page():
    st.title('Login Page')
    username = st.text_input('Username:')
    password = st.text_input('Password:', type='password')
    role = st.radio('Login as:', ['Patient', 'Doctor'])

    if st.button('Login'):
        if role == 'Patient' and username == 'patient' and password == 'password':
            session_state.username = username
            session_state.is_doctor = False
            st.success('Patient login successful!')
            st.experimental_rerun()
        elif role == 'Doctor' and username == 'doctor' and password == 'password':
            session_state.username = username
            session_state.is_doctor = True
            st.success('Doctor login successful!')
            st.experimental_rerun()
        else:
            st.error('Invalid credentials')

def signup_page():
    st.title('Signup Page')
    role = st.radio('Signup as:', ['Patient', 'Doctor'])
    new_username = st.text_input('New Username:')
    new_password = st.text_input('New Password:', type='password', key='signup_password')
    confirm_password = st.text_input('Confirm Password:', type='password', key='signup_confirm_password')

    if role == 'Doctor':
        doctor_name = st.text_input('Doctor Name:')
        doctor_id = st.text_input('Doctor ID:')
        
    if st.button('Sign Up'):
        if new_password == confirm_password:
            if role == 'Patient':
                st.success('Patient signup successful! Please log in.')
            elif role == 'Doctor':
                st.success('Doctor signup successful! Please log in.')
        else:
            st.error('Password and Confirm Password do not match.')

def patient_page():
    st.title('Patient Page')
    st.write(f'Welcome, {session_state.username} (Patient)!')
    st.button('Generate PDF', on_click=generate_pdf)

def doctor_page():
    st.title('Doctor Page')
    st.write(f'Welcome, {session_state.username} (Doctor)!')
    st.button('Generate PDF', on_click=generate_pdf)

def generate_pdf():
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt=f"Generated by: {session_state.username}", ln=True, align='C')
    pdf.output(f"{session_state.username}_evidence.pdf")

# Initialize the session state
session_state = SessionState()

# Sidebar navigation
page = st.sidebar.radio('Navigation', ['Login', 'Signup', 'Patient Page', 'Doctor Page'])

# Main application
if page == 'Login':
    login_page()
elif page == 'Signup':
    signup_page()
elif page == 'Patient Page':
    if session_state.username and not session_state.is_doctor:
        patient_page()
    else:
        st.warning('Please log in as a patient.')
elif page == 'Doctor Page':
    if session_state.username and session_state.is_doctor:
        doctor_page()
    else:
        st.warning('Please log in as a doctor.')
